# Model arguments
model_name_or_path: /mnt/scratch/home/ismayilz/project-cpo/models/cpo-sft-llama-3.1-8b-instruct-lora-fa-ms30
dataset_name: CNCL-Penn-State/cpo_en_multitask_text_fa_msd5_mm10_div_nov_sur
dataset_train_split: train
dataset_test_split: val_sample1024
output_dir: /mnt/scratch/home/ismayilz/project-cpo/models/cpo-dpo-sft-ms30-llama-3.1-8b-instruct-fa-msd5-mm10-nov

# Training arguments
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
learning_rate: 5.0e-7
num_train_epochs: 1
gradient_checkpointing: true
gradient_accumulation_steps: 4
lr_scheduler_type: cosine
weight_decay: 1.0e-3
logging_steps: 8
eval_strategy: steps
eval_steps: 16
save_strategy: steps
save_steps: 512
save_total_limit: 1
max_length: 1024
report_to: wandb
run_name: cpo-dpo-sft-ms30-llama-3.1-8b-instruct-fa-msd5-mm10-nov
dataloader_num_workers: 4
dataloader_prefetch_factor: 2
seed: 42
torch_empty_cache_steps: 16
remove_unused_columns: false
fp16: true
lambda_novelty: 1.0