# Model arguments
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
dataset_name: CNCL-Penn-State/cpo_en_multitask_text_msd5_xsd30_mm10_unif_eval
dataset_train_split: po_train
dataset_test_split: val_sample1024
output_dir: /mnt/scratch/home/ismayilz/project-cpo/models/cpo-dpo-llama-3.1-8b-instruct-msd5-xsd30-mm10

# Training arguments
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
num_train_epochs: 1
gradient_checkpointing: true
gradient_accumulation_steps: 4
learning_rate: 5.0e-7
lr_scheduler_type: cosine
weight_decay: 1.0e-3
logging_steps: 8
eval_strategy: steps
eval_steps: 16
save_strategy: steps
save_steps: 256
save_total_limit: 1
max_length: 1024
report_to: wandb
run_name: cpo-dpo-llama-3.1-8b-instruct-msd5-xsd30-mm10
dataloader_num_workers: 4
dataloader_prefetch_factor: 2
resume_from_checkpoint: true
torch_empty_cache_steps: 16
seed: 42
remove_unused_columns: false
fp16: true